name: generic_converters_env
channels:
  - http://conda.anaconda.org/gurobi
  - defaults
  - conda-forge
dependencies:
  - asn1crypto=1.3.0
  - boto3=1.11.0
  - botocore=1.14.0
  - ca-certificates=2020.1.1
  - certifi=2019.11.28
  - cffi=1.13.2
  - click=7.0
  - cryptography=2.8
  - docutils=0.15.2
  - flask=1.1.1
  - idna=2.8
  - itsdangerous=1.1.0
  - jinja2=2.10.3
  - jmespath=0.9.4
  - libcxx=4.0.1
  - libcxxabi=4.0.1
  - libedit=3.1.20181209
  - libffi=3.2.1
  - markupsafe=1.1.1
  - ncurses=6.1
  - openssl=1.1.1d
  - pip=19.3.1
  - pycparser=2.19
  - pyopenssl=19.1.0
  - pysocks=1.7.1
  - python=3.8.0
  - python-dateutil=2.8.1
  - readline=7.0
  - s3transfer=0.3.0
  - setuptools=44.0.0
  - six=1.14.0
  - sqlite=3.30.1
  - tk=8.6.8
  - urllib3=1.25.8
  - werkzeug=0.16.0
  - wheel=0.33.6
  - xz=5.2.4
  - zlib=1.2.11
